import type { ImageAdmissionMode } from '../harness/types.ts'

export type ImageMode = ImageAdmissionMode

export interface ImageAdmissionConfig {
  readonly maxImageBytes: number
  readonly maxImagesPerMessage: 20
  readonly maxMessageImageBytes: number
  readonly maxImagePixels: 64_000_000
  readonly maxImageDimension: 8192
  readonly normalizedImageMaxDimension: 2048
  readonly normalizedImageMaxBytes: number
  readonly imageCompressionConcurrency: 1 | 2
}

const commonConfig = {
  maxImagesPerMessage: 20,
  maxMessageImageBytes: 200 * 1024 * 1024,
  maxImagePixels: 64_000_000,
  maxImageDimension: 8192,
  normalizedImageMaxDimension: 2048,
  normalizedImageMaxBytes: 4 * 1024 * 1024,
} as const

export function resolveImageConfig(mode: ImageMode): ImageAdmissionConfig {
  if (mode === 'standard') {
    return Object.freeze({
      maxImageBytes: 20 * 1024 * 1024,
      ...commonConfig,
      imageCompressionConcurrency: 2,
    })
  }
  if (mode === 'large') {
    return Object.freeze({
      maxImageBytes: 64 * 1024 * 1024,
      ...commonConfig,
      imageCompressionConcurrency: 1,
    })
  }
  throw new TypeError(`unsupported image mode: ${String(mode)}`)
}

export function renderManagedImagePatch(mode: ImageMode): string {
  const config = resolveImageConfig(mode)
  return [
    '# Generated by LDD. Changes to this file are replaced when LDD settings change.',
    '# User-owned Harness patches remain in the separate home/profile cordis.patch.yml files.',
    '- id: attachment-local',
    '  config:',
    `    maxImageBytes: ${String(config.maxImageBytes)}`,
    `    maxImagesPerMessage: ${String(config.maxImagesPerMessage)}`,
    `    maxMessageImageBytes: ${String(config.maxMessageImageBytes)}`,
    `    maxImagePixels: ${String(config.maxImagePixels)}`,
    `    maxImageDimension: ${String(config.maxImageDimension)}`,
    `    normalizedImageMaxDimension: ${String(config.normalizedImageMaxDimension)}`,
    `    normalizedImageMaxBytes: ${String(config.normalizedImageMaxBytes)}`,
    `    imageCompressionConcurrency: ${String(config.imageCompressionConcurrency)}`,
    '- insert:',
    '    - id: ldd-video-frame-analyzer',
    "      name: '@ldd/dsh-video-frame-analyzer'",
    '      config:',
    '        provider: deepseek-official',
    '        model: deepseek-v4-flash-vision-exp',
    '        defaultPrecision: balanced',
    '        maxTokens: 2000',
    '        timeoutMs: 120000',
    '        ffmpegPath: !!js process.env.LDD_FFMPEG_PATH',
    '        ffprobePath: !!js process.env.LDD_FFPROBE_PATH',
    "        cacheRoot: !!js dshHomePath('ldd-managed', 'cache', 'video')",
    '        sceneThreshold: 0.35',
    '        stopGraceMs: 3000',
    '    - id: ldd-video-frame-analyzer-invariant',
    "      name: '@ldd/dsh-video-frame-analyzer/invariant'",
    '    - id: ldd-video-analysis-skills',
    "      name: '@deepseek-ai/dsh-skill-filesystem'",
    '      config:',
    '        providerName: ldd-video',
    '        includeDefaultRoots: false',
    '        customSkillDirs:',
    `          - !!js "process.getBuiltinModule('node:path').join(process.getBuiltinModule('node:path').dirname(process.getBuiltinModule('node:module').createRequire(baseUrl).resolve('@ldd/dsh-video-frame-analyzer/package.json')), 'skills')"`,
    '        watch: false',
    '',
  ].join('\n')
}
